### ISSUE TITLE
PHP 8 missing in composer.json

### ISSUE THREAD

**Issue by Dwarfex** [laminas-api-tools/api-tools-documentation-swagger#24]
### Bug Report

Release of Version 1.4.0 claims to have PHP 8.0 compatibility.
Missing Version in composer.json

|    Q        |   A
|------------ | ------
| Version(s)  | 1.4.0

#### Summary

The release is missing the correct required PHP specifiactins in composer.json

#### Current behavior

The version 1.4.0 will not be installed with composer if you are running PHP 8.0

#### How to reproduce

Have PHP 8.0 running - try to install / upgrade package via composer.
Setup will break with: 
laminas-api-tools/api-tools-documentation-swagger 1.4.0 requires php ^7.3 -> your php version (8.0.3) does not satisfy that requirement.

#### Expected behavior

Package installs with running PHP 8

**Comment by Ocramius** [comment]
Seen https://github.com/laminas-api-tools/api-tools-rest/issues/14 ?
