### ISSUE TITLE
Reason for maximum and minimum values

### ISSUE THREAD

**Issue by tasselchof** [laminas-api-tools/api-tools-documentation-swagger#27]
Hi!

Why there there are two parameters:

https://github.com/laminas-api-tools/api-tools-documentation-swagger/blob/29fc8ad2fdc241fc77edbda630862a095468c038/src/Service.php#L163-L171

```
'minimum'     => 0,
'maximum'     => 1,
```

I have URL path like that:

```
{
            "in": "path",
            "name": "service_point_id",
            "description": "URL parameter service_point_id",
            "type": "string",
            "required": true
}
```

If I pass service_point_id = 230419 Swagger UI does not allow it as it is not passing this minimum and maximum values.

**Comment by Ocramius** [comment]
Handled in #29, thanks @tasselchof!
